### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by LitteRabbit-37** [linearmouse/linearmouse#468] opened 2023-05-12 18:42 UTC
### OS

macOS 13.3.1 (a) (Build 22E772610a)

### LinearMouse

v0.9.0

### Is your feature request related to a problem?

I would like to ba able to put macro/shortcut action to mouse buttons. Because I'm not able to zoom correctly with single buttons (not smart zoom).

### Describe the solution you'd like

I'd like to have the possibility to record shortcut/macro to mouse buttons like "cmd" + "-" to zoom in and "shift" + "cmd" + "=" to zoom out. I love the new feature you added "assign actions to mouse buttons". I would just love more option.

### Additional context

<img width="559" alt="Xnapper-2023-05-12-20 42 01" src="https://github.com/linearmouse/linearmouse/assets/133410979/b189c350-a1d1-4460-98c2-d2492b744b79">

**Comment by ericmerrill** [comment] 2023-06-26 20:52
I've been testing the patch posted over in #503 in v0.9.3-beta.1, and am seeing some weird behavior. I have set the MX3 button 5 to `"keyPress": ["shift", "command", "control", "i"]` or `"keyPress": ["shift", "command", "space"]`, triggering the Lasso app, and what I'm seeing is that the buttons command buttons seem to get stuck in whatever app I was trying relocate a window in. Like if I was in Chrome when I activated it, it command and space will stay 'stuck' in the app, and pressing w (without holding any modifier keys) will cause the front most tab to close. Quitting and reopening linear mouse is the only consistent way to clear it (sometimes pressing other keys will clear it, but not always).

@lujjjh Please let me know if I should report this in a new ticket, and/or if you need more information from me to be able to reproduce. Right now I can't guarantee it's not a problem with specific to Lasso, or some other interaction on my system.

**Comment by ericmerrill** [comment] 2023-06-26 21:11
I wonder if it is because Lasso comes to the foreground before key release events are issued, and so chrome is never told the keys were release? This is what I see in the logs:
```
2023-06-26 20:54:48 +0000	info	ButtonActions	Down keys: [⇧, ⌘, Space]
2023-06-26 20:54:48 +0000	info	ButtonActions	CGEvent flags updated to CGEventFlags(rawValue: 1179658)
...
2023-06-26 20:54:48 +0000	info	DeviceManager	Frontmost app changed: com.heavylightapps.lasso
2023-06-26 20:54:48 +0000	info	Device	Restore pointer speed for device: MX Master 3S (VID=0x046D, PID=0xB034): 0.068966
2023-06-26 20:54:48 +0000	info	Device	Restore pointer acceleration for device: MX Master 3S (VID=0x046D, PID=0xB034): 1.000000
2023-06-26 20:54:48 +0000	info	Device	Update pointer acceleration for device: MX Master 3S (VID=0x046D, PID=0xB034): 1.000000
2023-06-26 20:54:48 +0000	info	Device	Restore pointer speed for device: Apple Internal Keyboard / Trackpad (VID=0x05AC, PID=0x0343): 0.068966
2023-06-26 20:54:48 +0000	info	Device	Restore pointer acceleration for device: Apple Internal Keyboard / Trackpad (VID=0x05AC, PID=0x0343): 0.687500
2023-06-26 20:54:48 +0000	info	Device	Update pointer acceleration for device: Apple Internal Keyboard / Trackpad (VID=0x05AC, PID=0x0343): 0.687500
...
2023-06-26 20:54:48 +0000	info	ButtonActions	Up keys: [⇧, ⌘, Space]
2023-06-26 20:54:50 +0000	info	DeviceManager	Frontmost app changed: com.google.Chrome
2023-06-26 20:54:50 +0000	info	Device	Restore pointer speed for device: MX Master 3S (VID=0x046D, PID=0xB034): 0.068966
2023-06-26 20:54:50 +0000	info	Device	Restore pointer acceleration for device: MX Master 3S (VID=0x046D, PID=0xB034): 1.000000
2023-06-26 20:54:50 +0000	info	Device	Update pointer acceleration for device: MX Master 3S (VID=0x046D, PID=0xB034): 1.000000
2023-06-26 20:54:50 +0000	info	Device	Restore pointer speed for device: Apple Internal Keyboard / Trackpad (VID=0x05AC, PID=0x0343): 0.068966
2023-06-26 20:54:50 +0000	info	Device	Restore pointer acceleration for device: Apple Internal Keyboard / Trackpad (VID=0x05AC, PID=0x0343): 0.687500
2023-06-26 20:54:50 +0000	info	Device	Update pointer acceleration for device: Apple Internal Keyboard / Trackpad (VID=0x05AC, PID=0x0343): 0.687500
2023-06-26 20:54:50 +0000	info	ButtonActions	CGEvent flags updated to CGEventFlags(rawValue: 1179658)
2023-06-26 20:54:51 +0000	info	ButtonActions	CGEvent flags updated to CGEventFlags(rawValue: 1179658)
2023-06-26 20:54:51 +0000	info	ButtonActions	CGEvent flags updated to CGEventFlags(rawValue: 1179658)
2023-06-26 20:54:53 +0000	info	ButtonActions	CGEvent flags updated to CGEventFlags(rawValue: 1179658)
2023-06-26 20:54:53 +0000	info	ButtonActions	CGEvent flags updated to CGEventFlags(rawValue: 1179658)
2023-06-26 20:54:53 +0000	info	ButtonActions	CGEvent flags updated to CGEventFlags(rawValue: 1179658)
2023-06-26 20:54:53 +0000	info	ButtonActions	CGEvent flags updated to CGEventFlags(rawValue: 1179658)
```

But I don't know enough about how LinearMouse is pushing the keypresses into the system to say if this disconnect between where the keys are pressed vs released could be causing the issue.

**Comment by lujjjh** [comment] 2023-06-27 03:54
@ericmerrill Thank you! I'll investigate this issue later.

**Comment by lujjjh** [comment] 2023-07-01 08:18
@ericmerrill LinearMouse [v0.9.3-beta.2](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.3-beta.2) has resolved this issue.

**Comment by ericmerrill** [comment] 2023-07-01 14:51
@lujjjh Can confirm - fixed now. Thank you so much!

**Closed** 2023-07-08 13:59 UTC
Labels: enhancement
