### ISSUE TITLE
hope to support page up/down

### ISSUE THREAD

**Issue by xenonz95** [linearmouse/linearmouse#501] opened 2023-06-15 07:51 UTC
### Describe the solution you'd like

I hope to be able to bind the mouse buttons to page up and page down in the settings.

**Comment by xenonz95** [comment] 2023-06-15 07:53
Sorry, I'm not familiar with posting issues. My OS is 13.4 and the LinearMouse version is 0.9.1.

**Comment by lujjjh** [comment] 2023-06-16 00:12
Thank you for your feedback. It appears that this is a duplicate of #468.

**Closed** 2023-07-08 13:59 UTC
Labels: enhancement
