### ISSUE TITLE
MIssion Control not working when linear mouse is working in the background

### ISSUE THREAD

**Issue by angaylo22** [linearmouse/linearmouse#559] opened 2023-08-01 15:00 UTC
### OS

MacOS 13.4.1 (c) (22F770820d)

### LinearMouse

0.9.3

### Describe the bug

When linearmouse is active the shortcuts for mission control no longer work.

I do not have any settings enabled on linear mouse that use and of the mission control features (mission control and Move Left/Right a Space) Though adding that feature to a button on the mouse seems to allow me to use mission control but not in the traditional shortcut way. 

Quitting linearmouse solves the issue but reopening it brings it back

The bug doesnt happen on its own by opening the program, It happens after clicking on any window, doesn't have to be linear mouse 

### Poorly Recorded Demonstration 

https://youtube.com/shorts/bD4XpRacYVA?feature=share

### To reproduce

1. Open linear mouse
2. Click on either the Icon on the bar or open preferences
2. Alternatively Click on any application other than linear mouse
3. Issue persists until quitting linearmouse even if not focused on any application

### Expected behavior

Mission control works by using the shortcut ctrl + arrow keys without having to quit linear mouse

**Comment by lujjjh** [comment] 2023-08-01 15:41
Thanks for your feedback!

I have watched the video and the problem is quite clear. However, it seems strange that I am unable to reproduce it on my end.

Could you please try to reproduce this issue and export the logs in the General panel? I will check if there is any useful information in them.

**Comment by hexial** [comment] 2023-08-01 20:12
I also have an issue with Ctrl not working. Attaching my logs from General panel.
[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/12233616/LinearMouse.log)

**Comment by lujjjh** [comment] 2023-08-02 13:38
Thank you @hexial!

Everything in the log looks normal, except I'm not sure what LogiVirtualHIDDevice is, but it doesn't seem like it would cause the <kbd>control</kbd> to fail.

Are you using an external keyboard or the built-in one? And. have you encountered the same situation as @angaylo22 where this issue happens not until the Settings window is open?

**Comment by angaylo22** [comment] 2023-09-06 10:28
[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/12536301/LinearMouse.log)
Sorry, I have not logged into GitHub for a while. I installed the 9.4.0 update and recreated it, here are the logs. 
I have now figured out the issue to recreate it properly
Use the same exact steps top reproduce, however I forgot to mention that I have this:
![image](https://github.com/linearmouse/linearmouse/assets/126945052/c936452f-0313-4d42-807d-00bafde0ea51)
removing it fixed the issue and re-adding it brings it back.
hopefully It is possible to fix.

**Comment by angaylo22** [comment] 2023-09-06 10:30
I will also note it does not happen on linear mouse v9.2.0

**Comment by lujjjh** [comment] 2023-09-06 13:58
@angaylo22 Thank you! I can confirm that this bug exists.

**Comment by lujjjh** [comment] 2023-09-07 05:58
The fix will be included in the next beta release.

**Closed** 2023-09-07 05:58 UTC
Labels: bug

**Comment by lujjjh** [comment] 2023-09-07 11:14
Please upgrade to [v0.9.5-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.5-beta.1) and see if this bug is resolved.
