### ISSUE TITLE
Mid-session unplug/replug events sometimes cause LinearMouse to not work properly.

### ISSUE THREAD

**Issue by jiroumu** [linearmouse/linearmouse#48] opened 2022-01-07 20:36 UTC
Hey lujjjh,

first of all I'd like to thank you for the great work you've been doing with LinearMouse, it has been a treat so far.

During a session LinearMouse starts working fine after sign-on. When I unplug and later replug my mouse (I use a USB-switch to use the same mouse between computers, effectively constituting a plug-cycle as far as I can tell), LinearMouse will sometimes not function properly and won't apply the set preferences. Plug-cycling the mouse again sometimes brings function back. When it works, it keeps working without intermittent failure, only plug-cycling triggers it. 

I've found that when plug-cycling and NOT touching the mouse for a few seconds until I'm sure the device switch is completed, LinearMouse again tends to work more often than not. When moving the mouse during a plug-cycle, LinearMouse seems to work less often coming back. Might just be my imagination, though.

**Comment by lujjjh** [comment] 2022-01-08 10:29
Hi @jiroumu,

Thank you for submitting this!

> LinearMouse will sometimes not function properly and won't apply the set preferences.

Do you mean that when you plug your mouse, the cursor acceleration and sensitivity aren't updated correctly?

That's possible. LinearMouse scans mice and adjusts their cursor acceleration and sensitivity every 5 seconds. So if you move your mouse right after plugging it in, LinearMouse may not have updated its cursor settings. When I get time, I'll improve this.

However, everything should works fine in 5 seconds without replugging the mouse. Could you please verify this?

**Comment by collinkreutzer** [comment] 2022-01-08 11:00
I have had similar issues before where LinearMouse would not apply acceleration and sensitivity correctly before replugging the usb receiver of my mouse. Restarting LinearMouse or waiting did not solve the issue. Only replugging did. Sadly i don't know how to reproduce this behavior reliably yet and it occurred only very sporadically.

This might have to do with my Thunderbolt Dock though, as my USB audio interface is also sometimes reset to full volume after waking my MacBook connected to the Dock.

**Comment by lujjjh** [comment] 2022-01-08 11:16
Thank you, @collinkreutzer! I'm trying to reproduce this issue.

If someone has reproduced it, [the logs](https://github.com/lujjjh/LinearMouse/issues/33#issuecomment-994244348) might assist me in determining what's going on.

**Comment by jiroumu** [comment] 2022-01-08 13:24
> Do you mean that when you plug your mouse, the cursor acceleration and sensitivity aren't updated correctly?

That's correct. For me, the issue only occurs when I unplug my mouse and replug it, then sometimes it won't be updated correctly, but it's hard to reproduce actually.

> However, everything should works fine in 5 seconds without replugging the mouse. Could you please verify this?
> If someone has reproduced it, the logs might assist me in determining what's going on.

I was trying just now as per your instructions regarding the console. Will update when I've been successful in reproducing the issue or catching misbehavior in the console.

**Comment by lujjjh** [comment] 2022-01-08 18:32
I've optimized the code. LinearMouse now receives notifications of device additions and removals. After plugging in USB receivers, cursor acceleration and sensitivity will be applied immediately. You may try [the binary here](https://github.com/lujjjh/LinearMouse/actions/runs/1671927046).

I'm not sure if this issue has been fixed as I couldn't reproduce it. If it still exists in [this version](https://github.com/lujjjh/LinearMouse/actions/runs/1671927046), please let me know.

Thank you!

**Comment by jiroumu** [comment] 2022-01-08 21:58
> I'm not sure if this issue has been fixed as I couldn't reproduce it. If it still exists in [this version](https://github.com/lujjjh/LinearMouse/actions/runs/1671927046), please let me know.

Your efforts are much appreciated. I've installed and will report back with my findings.

Cheers.

**Comment by jiroumu** [comment] 2022-01-13 09:18
Alright, I managed to reproduce the issue on the newest version. See the attached screenshot of the Console log. The log starts in a state where I just plug-cycled the mouse and LinearMouse wouldn't update sensitivity/acceleration due to it mistaking the mouse as a trackpad. After unplugging and replugging again, everything goes back to working as expected again, as can be seen in the later half of the log.

Hope this helps
<img width="1385" alt="console" src="https://user-images.githubusercontent.com/65429375/149301201-1e4fa311-7b52-41d8-bbbb-0a22f9fcc3e4.png">
.

**Comment by lujjjh** [comment] 2022-01-13 09:40
@jiroumu Thank you very much for the screenshot!

It seems that there are two devices named “Orochi V2”, one is treated as a mouse and the other a trackpad. It could be possible, I think, though my USB receiver registers only one mouse device.

Could you please check the log when everything works as expected? I couldn't see the log after the two “Orochi V2” are detected.

**Comment by jiroumu** [comment] 2022-01-13 10:22
Sure, find the attached screenshot of Console in a state where everything works as expected. Also attached is a screenshot from System Information listing the USB tree including the mouse receiver
<img width="1385" alt="console3" src="https://user-images.githubusercontent.com/65429375/149312103-ad1e9b6e-0b7d-4168-b904-86ea141ca25f.png">
<img width="251" alt="USB" src="https://user-images.githubusercontent.com/65429375/149312097-1d0f0adf-d0bf-4472-89e7-618aad3215e9.png">
.

**Comment by lujjjh** [comment] 2022-01-13 11:51
Thank you for providing this helpful information! At least, I know that both “Orochi V2” are expected to be mice.

It's odd that one of the “Orochi V2” service sometimes doesn't contain the mouse acceleration value by which LinearMouse detects trackpads:

https://github.com/linearmouse/linearmouse/blob/aa29cd7ff6b37586fa04190f834f308c817d6293/LinearMouse/CursorManager.swift#L99-L102

I'll experiment with changing the method LinearMouse identifies trackpads to see whether it works in this case.

Perhaps I should create a user interface for debugging as well.

**Comment by jiroumu** [comment] 2022-02-15 23:55
> I've rework the mouse detection algorithm in #82. Would you like to try [this build](https://github.com/linearmouse/linearmouse/actions/runs/1848071725) and see if this issue still exists?

Thanks for still taking the time. To be honest, for whatever reason the issue hasn't reoccured for me for the last month or so. Not sure if it's connected to a macOS update or something else you've been doing/adding since then (I keep LinearMouse up to date via brew). So I'm not sure if I'd even be able to verify the proposed fix in your new build as of now :o

**Comment by lujjjh** [comment] 2022-02-16 03:24
I guess the credit should be given to macOS updates. Anyway, I'm glad you got rid of the problem :)

I'm closing this issue. Feel free to reopen it anytime if you need additional help.

**Closed by lujjjh** 2022-02-16 03:24 UTC
Labels: bug
