### ISSUE TITLE
Beta version problem

### ISSUE THREAD

**Issue by TigerCat-hu** [linearmouse/linearmouse#719] opened 2024-03-27 09:18 UTC
### OS

macOS 14.4.1 verzió (23E224 build)

### LinearMouse

v0.9.5

### Describe the bug

I returned to the stable version, because the movement of the mouse is terribly stuttering and choppy. Please see what the problem could be, thanks!
Mac Mini 2018, i7 cpu, 16 GB memory

**Comment by lujjjh** [comment] 2024-03-29 13:31
Could this possibly be a duplicate of #688?

**Comment by lujjjh** [comment] 2024-03-31 06:07
I have refined the implementation of per-display settings. Please verify if the issue has been fixed in [v0.10.0-beta.3](https://github.com/linearmouse/linearmouse/releases/tag/v0.10.0-beta.3).

**Comment by TigerCat-hu** [comment] 2024-04-01 14:07
Now works fine. No problem, no lag, etc. Thanks!

**Comment by TigerCat-hu** [comment] 2024-04-01 14:21
Sorry, I was away from the computer for a few days...

**Comment by lujjjh** [comment] 2024-04-01 15:26
No worries at all, I really appreciate your feedback! I'll go ahead and close this issue for now, but please feel free to reopen it if you have any further questions or issues :)

**Closed by lujjjh** 2024-04-01 15:26 UTC
Labels: bug
