### ISSUE TITLE
Show in menubar has no effect  - macOS Ventura

### ISSUE THREAD

**Issue by polloralph** [linearmouse/linearmouse#277] opened 2022-11-07 16:15 UTC
I have the application set to hide the icon in the menu bar, but regardless of the setting, the icon persists. 
Restart has no effect.

**Comment by polloralph** [comment] 2022-11-08 02:33
M1 Macbook Pro

**Comment by lujjjh** [comment] 2022-11-08 02:37
Hi, @polloralph!

Thank you for your feedback.

Maybe duplicates of #271.

**Comment by matthewperiut** [comment] 2022-11-09 21:53
@lujjjh Can confirm, was a duplicate of #271, I also have a m1 macbook pro, and the issue was resolved after updating to 0.7.5.

**Closed** 2023-01-07 01:31 UTC
