### ISSUE TITLE
[bug]Changing acceleration doesn't work

### ISSUE THREAD

**Issue by Dr-Octopus-dev** [linearmouse/linearmouse#130] opened 2022-06-02 04:22 UTC
I'm sure LinearMouse doesn't work, because in contrast, I can successfully turn off the acceleration with CursorSense.

**Comment by lujjjh** [comment] 2022-06-02 05:18
You may need to provide additional information to help troubleshoot this problem. Your macOS version and the pointer device you're using, for example. Also, [the logs](https://github.com/linearmouse/linearmouse/discussions/117) from when you turned off the acceleration might be useful.

BTW, CursorSense and LinearMouse are incompatible. It's possible that one of them doesn't work correctly if both are installed.

**Comment by Dr-Octopus-dev** [comment] 2022-06-02 05:38
macOS 12.4
trackpad
I tried uninstalling CursorSense and SteerMouse and re-selected accessibility options, but it still doesn't work.

**Comment by lujjjh** [comment] 2022-06-02 05:46
Duplicate of #65.

For the time being, LinearMouse is only for mice and will not affect trackpads.

**Comment by Dr-Octopus-dev** [comment] 2022-06-02 05:50
>  Also, [the logs](https://github.com/linearmouse/linearmouse/discussions/117) from when you turned off the acceleration might be useful.
I've checked the Console. However, when I change the acceleration and speed options, there are no new logs, but only some logs at startup, such as:
默认	13:42:40.396939+0800	LinearMouse	SetFrontProcess: asn=0x0-0x55c55c options=1
默认	13:43:40.499237+0800	LinearMouse	SetFrontProcess: asn=0x0-0x55c55c options=1
默认	13:44:33.372448+0800	LinearMouse	Entering exit handler.
默认	13:44:33.372467+0800	LinearMouse	Exiting exit handler.
默认	13:44:35.931972+0800	LinearMouse	Received configuration update from daemon (initial)
默认	13:44:35.935945+0800	LinearMouse	CHECKIN: pid=82717
默认	13:44:35.948321+0800	LinearMouse	CHECKEDIN: pid=82717 asn=0x0-0x641641 foreground=0
默认	13:44:35.951226+0800	LinearMouse	FRONTLOGGING: version 1
默认	13:44:35.951261+0800	LinearMouse	Registered, pid=82717 ASN=0x0,0x641641
默认	13:44:35.955384+0800	LinearMouse	BringForward: pid=82717 asn=0x0-0x641641 bringForward=0 foreground=0 uiElement=1 launchedByLS=1 modifiersCount=1 allDisabled=0
默认	13:44:35.955625+0800	LinearMouse	BringFrontModifier: pid=82717 asn=0x0-0x641641 Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
默认	13:44:35.956191+0800	LinearMouse	Current system appearance, (HLTB: 1), (SLS: 0)
默认	13:44:35.958904+0800	LinearMouse	No persisted cache on this platform.
默认	13:44:35.961993+0800	LinearMouse	Post-registration system appearance: (HLTB: 1)
错误	13:44:36.022955+0800	LinearMouse	Error: Serving updates without an EdDSA key and only using Apple Code Signing is deprecated and may be unsupported in a future release. Visit Sparkle's documentation for more information: https://sparkle-project.org/documentation/#3-segue-for-security-concerns
默认	13:44:36.027988+0800	LinearMouse	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600002931e00
 (
    "<NSAquaAppearance: 0x600002931f80>",
    "<NSSystemAppearance: 0x60000292d280>"
)>
默认	13:44:36.081542+0800	LinearMouse	Registering for test daemon availability notify post.
默认	13:44:36.081686+0800	LinearMouse	notify_get_state check indicated test daemon not ready.
默认	13:44:36.081759+0800	LinearMouse	notify_get_state check indicated test daemon not ready.
默认	13:44:36.081999+0800	LinearMouse	notify_get_state check indicated test daemon not ready.
默认	13:44:36.090801+0800	LinearMouse	Recieved DFR status change 0. status = 0x1
默认	13:44:36.091799+0800	LinearMouse	Recieved DFR status change 1. status = 0x1
默认	13:44:36.095626+0800	LinearMouse	SignalReady: pid=82717 asn=0x0-0x641641
默认	13:44:36.096901+0800	LinearMouse	SIGNAL: pid=82717 asn=0x0x-0x641641
默认	13:44:36.118535+0800	LinearMouse	Reacting to DFR status change 0. status = 0x1
默认	13:44:36.123020+0800	LinearMouse	Shortcuts Contextual Actions enabled
默认	13:44:36.123491+0800	LinearMouse	Reacting to DFR status change 1. status = 0x1
默认	13:44:43.429475+0800	LinearMouse	SetFrontProcess: asn=0x0-0x641641 options=1
默认	13:44:53.720163+0800	LinearMouse	LSExceptions shared instance invalidated for timeout.

**Comment by Dr-Octopus-dev** [comment] 2022-06-02 05:57
> Duplicate of #65.
> 
> For the time being, LinearMouse is only for mice and will not affect trackpads.

Oh, I see.

**Comment by lujjjh** [comment] 2022-06-02 07:28
> I've checked the Console. However, when I change the acceleration and speed options, there are no new logs, but only some logs at startup [...]

It seems that you haven't [enabled debug messages](https://github.com/linearmouse/linearmouse/discussions/117#:~:text=Select%20View%20%E2%86%92%20Include%20Debug%20Messages.). Debug messages are not displayed by default.

Anyway, I think we'll now close this issue and track this feature in #65.

Thank you for your feedback!

**Closed by lujjjh** 2022-06-02 07:28 UTC
